spring:
  datasource:
    url: jdbc:mariadb://192.168.56.109:3306/jwtDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: gfhjkm
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect
server:
  port: 8097