jwt:
  secret: jwtsecretkey
spring:
  datasource:
    password: gfhjkm
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/jwt?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
