logging:
  file: /tmp/spring/example/application.log
  level:
    root: WARN
    spring.example: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
      port: 8084
