spring:
  h2:
    console.enabled: true
    console.path: /h2-console

  datasource:
    initialize: true
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    properties.hibernate:
      format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: h2